name: test

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.35
        args: --verbose

  cross:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Cross"
      run: make artifacts

  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Install isolation plugin"
      run: |
        make
        sudo make install
    - name: "Install other plugins"
      run: |
        sudo mkdir -p /opt/cni/bin
        curl -L https://github.com/containernetworking/plugins/releases/download/v0.9.0/cni-plugins-linux-amd64-v0.9.0.tgz | sudo tar xzvC /opt/cni/bin
    - name: "Test"
      run: |
        go test -c ./plugins/meta/isolation
        sudo PATH=/opt/cni/bin:$PATH ./isolation.test -test.v -ginkgo.v
